# Copyright 2023 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

services:
  # See the Dockerfile for the port it listens to
  kvserver:
    build:
      context: ../..
      dockerfile: getting_started/quick_start_assets/Dockerfile.server
    network_mode: host
    security_opt:
      - seccomp:unconfined
  # envoy proxy specific to the K/V server instance
  # See the yaml file for the configured port it listens to
  kv-envoy-proxy:
    image: envoyproxy/envoy:distroless-v1.26-latest
    network_mode: host
    command:
    - -c
    - /etc/envoy/envoy.yaml
    depends_on:
      kvserver:
        condition: service_started
    volumes:
    - type: bind
      read_only: true
      source: ../../components/envoy_proxy/envoy.yaml
      target: /etc/envoy/envoy.yaml
    - type: bind
      read_only: true
      source: ../../dist/query_api_descriptor_set.pb
      target: /etc/envoy/query_api_descriptor_set.pb